spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true #system out으로 출력 (org.hibernate.SQL과 비교)
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #logger로 출력(show_sql과 비교)
    org.hibernate.type: trace